---
name: Build and Upload

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet build HelloWorldV2.csproj
        name: build app
      - uses: actions/upload-artifact@v3
        name: upload artifact
      - run: dotnet test
        name: run tests
