name: Build-App

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
        run: dotnet build HelloWorld2.csproj
