name: Deploy to Kubernetes
on:
  workflow_run:
    workflows: ["Build and Upload"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_SEC }}
          
      - name: Verify Kubernetes connection
        run: kubectl get nodes
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubedeploy.yml
          kubectl rollout restart deployment/tom-deploy
          
      - name: Verify deployment
        run: |
          kubectl get deployment tom-deploy
          kubectl get pods -l app=tom-me