name: Deploy to Kubernetes
on:
  workflow_run:
    workflows: ["Build and Upload"]
    types:
      - completed
    branches:
      - main
env:
  KUBE_CONFIG: ${{ secrets.KUBE_SEC }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Get deployments
        uses: actions-hub/kubectl@master
        with:
          args: get deployment
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy yml
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubedeploy.yml
      - name: Get deployments
        uses: actions-hub/kubectl@master
        with:
          args: get deployment