name: Deploy to Kubernetes
on:
  workflow_run:
    workflows: ["Build and Upload"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_SEC }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
      - name: Verify Kubernetes connection
        run: |
          echo "Testing connection to cluster..."
          kubectl config view --minify
          kubectl get nodes
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubedeploy.yml
          kubectl rollout restart deployment/tom-deploy
          
      - name: Verify deployment
        run: |
          kubectl get deployment tom-deploy
          kubectl get pods -l app=tom-me